/**
 * storageCleanup.service.js
 *
 * Cascading B2 storage cleanup when DB records are deleted.
 *
 * Each image upload lands in its own UUID sub-directory:
 *   images/{kind}/{userId}/{uuid}/{filename.ext}   ← original
 *   images/{kind}/{userId}/{uuid}/{filename}.thumbnail.webp
 *   images/{kind}/{userId}/{uuid}/{filename}.card.webp
 *   images/{kind}/{userId}/{uuid}/{filename}.full.webp
 *
 * Strategy: given a stored CDN/B2 URL, extract the directory prefix
 * (everything up to the last /), list all objects under it, and delete
 * them all. Because each upload uses a fresh UUID, this safely removes
 * the original + all three Sharp variants without touching anything else.
 *
 * Product ZIP files are stored as a raw key in `product.file.b2FileName`
 * and are deleted directly (no variants, no directory listing needed).
 */

const logger = require('../config/logger');
const b2 = require('./b2');
const appConfig = require('./appConfig.service');

/* ── Key extraction ─────────────────────────────────────────── */

/**
 * Recover the raw B2 object key from a stored URL.
 *
 * Three URL formats are possible depending on configuration:
 *   1. Proxy URL  — /uploads/proxy?key=images%2F...  (CDN_DOMAIN not set)
 *   2. CDN URL    — https://cdn.example.com/images/...
 *   3. Direct B2  — https://s3.region.backblazeb2.com/bucket/images/...
 *
 * Returns null for external / unrecognised URLs (safe to skip).
 */
function extractKey(url) {
  if (!url || typeof url !== 'string') return null;

  // 1. Proxy URL — generated by cdn.publicUrl() when CDN_DOMAIN is not configured.
  //    Format: {apiBase}/uploads/proxy?key=images%2Fproduct%2F{userId}%2F{uuid}%2F{file}
  const proxyMarker = '/uploads/proxy?key=';
  const proxyIdx = url.indexOf(proxyMarker);
  if (proxyIdx !== -1) {
    const encoded = url.slice(proxyIdx + proxyMarker.length).split('&')[0];
    return decodeURIComponent(encoded);
  }

  // Use the same runtime-resolved config that cdn.service.js uses so DB
  // overrides (set via admin Settings UI) are respected.
  const b2c = appConfig.get('b2') || {};

  // 2. CDN URL — https://{cdnDomain}/{key}
  if (b2c.cdnDomain && url.includes(b2c.cdnDomain)) {
    const i = url.indexOf(b2c.cdnDomain);
    return decodeURI(url.slice(i + b2c.cdnDomain.length + 1).split('?')[0]);
  }

  // 3. Direct B2 endpoint — https://{endpointHost}/{bucket}/{key}
  if (b2c.endpointHost && url.includes(b2c.endpointHost)) {
    const after = url.split(b2c.endpointHost)[1] || '';
    const parts = after.split('?')[0].replace(/^\/+/, '').split('/');
    parts.shift(); // drop bucket name
    return decodeURI(parts.join('/'));
  }

  // Bare key (no scheme) — some paths store raw keys
  if (!url.startsWith('http')) return url;

  return null; // external URL (Unsplash, etc.) — skip
}

/* ── Low-level delete ───────────────────────────────────────── */

async function del(key) {
  if (!key) return;
  try {
    await b2.deleteObject(key);
  } catch {
    // Already gone or never existed — not an error worth surfacing
  }
}

/* ── Image directory delete ─────────────────────────────────── */

/**
 * Delete an image AND all its Sharp variants by wiping the UUID directory.
 * Lists every object under `{prefix}/{uuid}/` and deletes them in parallel.
 * No-ops on null / external URLs.
 */
async function deleteImageDir(url) {
  const key = extractKey(url);
  if (!key) return;

  const lastSlash = key.lastIndexOf('/');
  if (lastSlash < 0) {
    // Flat key with no directory — delete directly
    await del(key);
    return;
  }

  const dirPrefix = key.slice(0, lastSlash + 1); // includes trailing /

  const keys = [];
  for await (const obj of b2.listAll(dirPrefix)) {
    keys.push(obj.Key);
  }

  await Promise.all(keys.map(del));
}

/* ── Entity-level helpers ───────────────────────────────────── */

/**
 * Delete all B2 assets tied to a product:
 *   • product ZIP  (product.file.b2FileName — direct key)
 *   • thumbnail    (CDN URL → dir wipe)
 *   • hoverImage   (CDN URL → dir wipe)
 *   • images[]     (CDN URLs → dir wipe each)
 */
async function deleteProductFiles(product) {
  const tasks = [];

  if (product.file?.b2FileName) {
    tasks.push(del(product.file.b2FileName));
  }
  if (product.thumbnail)  tasks.push(deleteImageDir(product.thumbnail));
  if (product.hoverImage) tasks.push(deleteImageDir(product.hoverImage));
  (product.images || []).forEach((u) => tasks.push(deleteImageDir(u)));

  const results = await Promise.allSettled(tasks);
  const failed = results.filter((r) => r.status === 'rejected');
  if (failed.length) {
    logger.warn('storageCleanup.deleteProductFiles: partial failure', {
      productId: String(product._id),
      errors: failed.map((r) => r.reason?.message),
    });
  }
}

/**
 * Delete all B2 assets tied to a bundle:
 *   • image    (CDN URL → dir wipe)
 *   • images[] (CDN URLs → dir wipe each)
 */
async function deleteBundleFiles(bundle) {
  const tasks = [];
  if (bundle.image) tasks.push(deleteImageDir(bundle.image));
  (bundle.images || []).forEach((u) => tasks.push(deleteImageDir(u)));
  await Promise.allSettled(tasks);
}

/**
 * Delete a single image field (blog cover, hero slide, brand logo, category image).
 */
async function deleteSingleImage(url) {
  if (url) await deleteImageDir(url);
}

module.exports = {
  extractKey,
  deleteProductFiles,
  deleteBundleFiles,
  deleteSingleImage,
};
