/**
 * Static seed payload — mirrors lexx-main/lib/data.ts and
 * lexxdadmin-main/lib/mock.ts so seeded DB matches what both
 * Next.js apps already render.
 */

const categories = [
  {
    name: '3D Models',
    slug: 'models',
    subs: ['Furniture', 'Lighting', 'Decor', 'Kitchen'],
    banners: [
      {
        img: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1800&q=90',
        title: 'Premium 3D Models Collection',
        sub: 'Production-ready furniture, lighting, and decor assets.',
      },
      {
        img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1800&q=90',
        title: 'Obsessive Detail & Fidelity',
        sub: 'Hand-crafted assets with high resolution maps.',
      },
      {
        img: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1800&q=90',
        title: 'V-Ray & Corona Compatibility',
        sub: 'Pre-configured shaders and materials for instant rendering.',
      },
    ],
  },
  {
    name: '3D Scenes',
    slug: 'scenes',
    subs: ['Interior', 'Exterior'],
    banners: [
      {
        img: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1800&q=90',
        title: 'Complete 3D Scenes',
        sub: 'Fully staged interior and exterior visualizer templates.',
      },
      {
        img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1800&q=90',
        title: 'Staged Lighting & Camera Setups',
        sub: 'Learn industry lighting styles directly from original staging.',
      },
    ],
  },
  { name: '3D Sets', slug: 'sets', subs: [] },
  { name: 'Textures', slug: 'textures', subs: ['Wood', 'Stone', 'Fabric'] },
  // Functional sub-cats used by products below
  { name: 'Sofas', slug: 'sofas', parent: 'models' },
  { name: 'Chairs', slug: 'chairs', parent: 'models' },
  { name: 'Decor', slug: 'decor-items', parent: 'models' },
  { name: 'Desks', slug: 'desks', parent: 'models' },
  { name: 'Interior', slug: 'interior', parent: 'scenes' },
  { name: 'Exterior', slug: 'exterior', parent: 'scenes' },
];

const brands = [
  { name: 'Villevenete', slug: 'villevenete', country: 'IT' },
  { name: 'Polflex', slug: 'polflex', country: 'PL' },
  { name: 'Arbore', slug: 'arbore', country: 'IT' },
  { name: 'Wall Deco', slug: 'wall-deco', country: 'DE' },
  { name: 'Marble Studio', slug: 'marble-studio', country: 'IT' },
  { name: 'K_Design', slug: 'k-design', country: 'NL' },
];

const products = [
  {
    slug: 'sofa-harlem',
    title: 'Sofa Harlem',
    brand: 'villevenete',
    categorySlug: 'sofas',
    price: 9043,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900',
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=900',
    ],
    views: 9695,
    likes: 1884,
    material: 'Fabric',
    style: 'Modern',
    color: 'Beige',
    description:
      'Elegant modular sofa with refined tailoring and generous proportions. Crafted for modern living rooms.',
    dimensions: { w: 240, l: 95, h: 82 },
    fileSizeMb: 118.7,
  },
  {
    slug: 'wall-deco-nature',
    title: 'SCENT OF NATURE B-6S',
    brand: 'wall-deco',
    categorySlug: 'decor-items',
    price: 359,
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=900'],
    views: 5784,
    likes: 836,
    material: 'Ceramic',
    style: 'Contemporary',
    color: 'White',
    description: 'Sculptural wall decoration inspired by natural forms.',
    fileSizeMb: 42.3,
  },
  {
    slug: 'office-chair-416',
    title: 'Office Chair 416',
    brand: 'polflex',
    categorySlug: 'chairs',
    price: 1297,
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600',
    images: ['https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=900'],
    views: 6751,
    likes: 781,
    material: 'Wood + Leather',
    style: 'Modern',
    color: 'Brown',
    description:
      'Ergonomic office chair with premium walnut frame and full-grain leather seat.',
    fileSizeMb: 76.1,
  },
  {
    slug: 'sofa-wimbledon',
    title: 'Sofa Wimbledon',
    brand: 'villevenete',
    categorySlug: 'sofas',
    price: 9429,
    image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600',
    images: ['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900'],
    views: 6689,
    likes: 1187,
    material: 'Leather',
    style: 'Classic',
    color: 'Black',
    description: 'Statement three-seat sofa upholstered in full-grain black leather.',
    fileSizeMb: 132.4,
  },
  {
    slug: 'office-desk-xander',
    title: 'Office Desk Xander',
    brand: 'arbore',
    categorySlug: 'desks',
    price: 0,
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=900',
      'https://images.unsplash.com/photo-1503602642458-232111445657?w=900',
    ],
    views: 3422,
    likes: 610,
    material: 'Wood',
    style: 'Modern',
    color: 'Walnut',
    description:
      "Commanding presence and sculptural lines — Xander is more than a desk. Crafted with the finest oak veneer, stained in rich American Walnut.",
    dimensions: { w: 180, l: 217, h: 82 },
    fileSizeMb: 118.7,
  },
  {
    slug: 'modular-sofa-achille',
    title: 'Modular Sofa Achille',
    brand: 'villevenete',
    categorySlug: 'sofas',
    price: 7820,
    image: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600',
    images: ['https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=900'],
    views: 4120,
    likes: 922,
    material: 'Velvet',
    style: 'Contemporary',
    color: 'Grey',
    description: 'Modular configuration with deep seats and soft velvet upholstery.',
    fileSizeMb: 95.2,
    status: 'draft',
  },
  {
    slug: 'barn-house-5',
    title: 'Barn House 5',
    brand: 'k-design',
    categorySlug: 'exterior',
    price: 1899,
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600',
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900'],
    views: 2834,
    likes: 410,
    style: 'Rustic',
    description: 'Full architectural scene of a barn-style country house with landscaping.',
    fileSizeMb: 512.0,
  },
  {
    slug: 'neoclassical-bathroom',
    title: 'Neoclassical Bathroom 44',
    brand: 'marble-studio',
    categorySlug: 'interior',
    price: 689,
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600',
    images: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900'],
    views: 3580,
    likes: 520,
    style: 'Neoclassical',
    description: 'Full bathroom scene with marble finishes and classical detailing.',
    fileSizeMb: 244.0,
  },
];

const bundles = [
  {
    slug: 'living-room-essentials',
    name: 'Living Room Essentials',
    tag: 'Most Popular',
    badge: 'Best Value',
    description:
      'Everything you need to furnish a complete living room scene. Three premium sofas, a statement desk, and a sculptural decor piece — all production-ready.',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=85',
    images: [
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=85',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85',
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=900&q=85',
    ],
    productSlugs: ['sofa-harlem', 'sofa-wimbledon', 'modular-sofa-achille', 'wall-deco-nature'],
    bundlePrice: 17900,
    fileSizeMb: 388.5,
    formats: ['.max', '.fbx', '.obj', '.skp'],
  },
  {
    slug: 'workspace-collection',
    name: 'Workspace Collection',
    tag: 'New Bundle',
    description:
      'A curated set of office and workspace assets — Xander desk, 416 ergonomic chair, complementary decor.',
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=85',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=900&q=85',
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=900&q=85',
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=900&q=85',
    ],
    productSlugs: ['office-desk-xander', 'office-chair-416', 'wall-deco-nature'],
    bundlePrice: 1990,
    fileSizeMb: 194.1,
    formats: ['.max', '.fbx', '.obj'],
  },
  {
    slug: 'architectural-scenes-pack',
    name: 'Architectural Scenes Pack',
    tag: 'Studio Pick',
    badge: 'Studio Exclusive',
    description:
      'Two complete architectural scenes — barn house exterior and neoclassical bathroom interior — plus the Villevenete sofa for staging.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=85',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=85',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&q=85',
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=900&q=85',
    ],
    productSlugs: ['barn-house-5', 'neoclassical-bathroom', 'modular-sofa-achille'],
    bundlePrice: 6990,
    fileSizeMb: 851.2,
    formats: ['.max', '.fbx', '.obj', '.skp'],
  },
  {
    slug: 'complete-interior-kit',
    name: 'Complete Interior Kit',
    tag: 'Ultimate Bundle',
    badge: 'Save 40%',
    description:
      'The most comprehensive interior bundle on Lexxus. All 8 flagship assets — sofas, chairs, desks, decor, and full scenes.',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=85',
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=900&q=85',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=900&q=85',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=900&q=85',
    ],
    productSlugs: [
      'sofa-harlem',
      'wall-deco-nature',
      'office-chair-416',
      'sofa-wimbledon',
      'office-desk-xander',
      'modular-sofa-achille',
      'barn-house-5',
      'neoclassical-bathroom',
    ],
    bundlePrice: 18900,
    fileSizeMb: 1850.0,
    formats: ['.max', '.fbx', '.obj', '.skp'],
  },
];

const blog = [
  {
    slug: 'multifunctional-family-space',
    title: 'Multifunctional Family Space Redefined with Deco Line 3D Wall Panels',
    excerpt: 'How modular panels transform shared living spaces.',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600',
    status: 'published',
  },
  {
    slug: 'studjo-wallart-croatian',
    title: 'Studjo Wallart: Croatian Art Transformed into Interior',
    excerpt: "A deep-dive into Studjo's material-first philosophy.",
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600',
    status: 'published',
  },
  {
    slug: 'gyform-where-beauty-meets-comfort',
    title: 'Gyform: Where Beauty Meets Comfort',
    excerpt: 'Italian craftsmanship for the modern home.',
    image: 'https://images.unsplash.com/photo-1567016526105-22da7c13161a?w=600',
    status: 'draft',
  },
  {
    slug: 'salini-premium-materials',
    title: 'Salini: Premium Materials and Manufacturing',
    excerpt: 'Behind the scenes at a premium bath brand.',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600',
    status: 'published',
  },
  {
    slug: 'fovere-sustainable-acoustics',
    title: 'Fovere: Sustainable Acoustic Solutions Made in Poland',
    excerpt: 'Eco-friendly sound design you can see.',
    image: 'https://images.unsplash.com/photo-1615529162924-f8605388461d?w=600',
    status: 'published',
  },
];

const heroSlides = [
  {
    order: 0,
    active: true,
    img: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1920&q=85',
    tag: 'New Collection',
    title: ['Premium 3D Assets', 'For Visualization Pros'],
    sub: 'Production-ready models, scenes, sets, and textures from world-class creators.',
    cta: 'Explore Models',
    href: '/models',
    accent: 'Free shipping · Instant download · Royalty-free',
  },
  {
    order: 1,
    active: true,
    img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=85',
    tag: 'Bundles',
    title: ['Save up to 40%', 'On curated bundles'],
    sub: 'Ship complete scenes faster with our hand-picked product bundles.',
    cta: 'Browse Bundles',
    href: '/bundles',
    accent: 'Best value · Studio picks',
  },
];

const users = [
  {
    name: 'Admin',
    email: 'admin@lexxus.com',
    password: 'admin12345',
    role: 'admin',
    verified: true,
  },
  {
    name: 'Lexxus Studio',
    email: 'studio@lexxus.com',
    password: 'studio12345',
    role: 'creator',
    verified: true,
    bio: 'Default creator account that owns all seeded products.',
  },
  {
    name: 'Alex Novak',
    email: 'alex@studio.io',
    password: 'buyer12345',
    role: 'buyer',
    verified: true,
  },
  {
    name: 'Maria Rossi',
    email: 'maria@rossi.it',
    password: 'buyer12345',
    role: 'buyer',
    verified: true,
  },
  {
    name: 'John Lee',
    email: 'j.lee@agency.com',
    password: 'buyer12345',
    role: 'buyer',
    verified: true,
  },
];

module.exports = { categories, brands, products, bundles, blog, heroSlides, users };
